### PR TITLE
Revised pyan trouble shooting.

### PR DESCRIPTION
**Pull request by darkrsw**
Fixed cell link and provided an example.

### CODE REVIEW

**Review by mboehme — COMMENTED** [review]
@vrthra and @darkrsw: Would it be safe to `pip install pyan3`. If so, we could always use pyan3, instead.

**Comment by darkrsw** [comment]
@darkrsw Agreed. But you need to check out it works in other systems such as Windows and Ubuntu.

**Comment by mboehme** [comment]
pip is a Python-specific package installation tool. Imo, it should work across platforms.

**Comment by darkrsw** [comment]
@mboehme I meant `pyan3` is compatible with other systems. macOS is fine but I didn't test it in other OSes.

**Comment by psybers** [comment]
Just fyi, I'm on macos (Big Sur 11.5.2, python 3.9.6 via brew) and had to actually use an older pyan3 (1.1.1 - not the latest 1.2.0) to get this working.

**Comment by psybers** [comment]
Is it possible to test for the executable and run `pyan` or `pyan3` based on which is installed?

**Comment by psybers** [comment]
Maybe something simple and hacky, like this:

````diff
-    "    os.system(f'pyan {file_name} --uses --defines --colored --grouped --annotated --dot > {cg_file}')\n",
+    "    if os.system(f'pyan {file_name} --uses --defines --colored --grouped --annotated --dot > {cg_file}') != 0:\n",
+    "        os.system(f'pyan3 {file_name} --uses --defines --colored --grouped --annotated --dot > {cg_file}')\n",
````

**Comment by vrthra** [comment]
The Pyan version we use is saved in the [uds-se organization](https://github.com/uds-se/fuzzingbook/blob/master/binder/environment.yml). So we should simply mention that one should always use that instead.

**Comment by andreas-zeller** [comment]
Hi @vrthra – can you take care of this?

**Comment by vrthra** [comment]
@andreas-zeller  sure I will do that.

**Pull request merged**
